# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\telas\inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inicio(object):
    def setupUi(self, Inicio):
        Inicio.setObjectName("Inicio")
        Inicio.resize(500, 500)
        Inicio.setMinimumSize(QtCore.QSize(500, 500))
        Inicio.setMaximumSize(QtCore.QSize(500, 500))
        Inicio.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(Inicio)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_img = QtWidgets.QLabel(self.centralwidget)
        self.lb_img.setGeometry(QtCore.QRect(160, 30, 171, 151))
        self.lb_img.setText("")
        self.lb_img.setPixmap(QtGui.QPixmap(".\\telas\\../img/akinator_complete-removebg-preview (2).png"))
        self.lb_img.setScaledContents(True)
        self.lb_img.setObjectName("lb_img")
        self.bt_iniciar = QtWidgets.QPushButton(self.centralwidget)
        self.bt_iniciar.setGeometry(QtCore.QRect(190, 200, 121, 51))
        self.bt_iniciar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Bosch Sans\";\n"
"border: 10px;\n"
"border-color: black;\n"
"border-radius: 10px;\n"
"color: black;")
        self.bt_iniciar.setObjectName("bt_iniciar")
        self.lb_logo = QtWidgets.QLabel(self.centralwidget)
        self.lb_logo.setGeometry(QtCore.QRect(380, 460, 111, 20))
        self.lb_logo.setObjectName("lb_logo")
        Inicio.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Inicio)
        self.statusbar.setObjectName("statusbar")
        Inicio.setStatusBar(self.statusbar)

        self.retranslateUi(Inicio)
        QtCore.QMetaObject.connectSlotsByName(Inicio)

    def retranslateUi(self, Inicio):
        _translate = QtCore.QCoreApplication.translate
        Inicio.setWindowTitle(_translate("Inicio", "Inicio"))
        self.bt_iniciar.setText(_translate("Inicio", "Iniciar"))
        self.lb_logo.setText(_translate("Inicio", "Produzido por: Alemão"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Inicio = QtWidgets.QMainWindow()
    ui = Ui_Inicio()
    ui.setupUi(Inicio)
    Inicio.show()
    sys.exit(app.exec_())
